<head>
  <style>
    html {
      font: 1em sans-serif;
      background: #7f7f7f;
      color: #ffff;
    }

    .input__text {
      width: 560px;
      height: 150px;
      color: red;
      background: #2f2f2f;
      border: 2px solid #ffff;
    }

    .title {
      color: #000;
      margin-bottom: 15px;
    }

    .message {
      width: 560px;
      background: #3f3f3f;
      border: 1px solid #000;
      margin-bottom: 10px;
    }

    .author {
      color: #000;
      text-decoration: underline;
    }

    .date {
      font-size: 11px;
      color: #d185a9;
      margin-left: 10px;
      margin-right: 5px;
    }

    .text {
      margin-left: 5px;
      padding: 10px 0px 15px 15px;
    }

    .field {
      display: flex;
      flex-direction: column;
      margin-bottom: 5px;
    }

    .button {
      margin-top: 10px;
      width: 200px;
      color: #d185a9;
      border-radius: 10px;
      padding: 10px
    }

    .admin {
      display: flex;
      justify-content: flex-end;
      margin-right: 5px;
      margin-bottom: 5px;
    }

    .admin a {
      color: red;
      text-decoration: none;
      background-color: #000;
      padding: 5px 5px;
      border-radius: 5px;
    }

    .img {
      max-width: 400px;
      max-height: 400px;
    }

    .logOut {
      display: flex;
      justify-content: flex-end;
    }

    .logOut a {
      color: red;
      text-decoration: none;
      background-color: #3f3f3f;
      padding: 5px 20px 5px 20px;
      border-radius: 5px;
    }
  </style>
</head>

<?php
$user = $this->user;
?>

<div class="logOut">
  <a href="/blog/logOut">Выйти</a>
</div>
<div class="title">Список сообщений:</div>
<? if ($messages = $this->messages) : ?>
  <? foreach ($messages as $message) : ?>
    <div class="message">
      <span class="date"><?= $message->getCreated_at(); ?></span>
      <? if ($author = $message->getAuthor()) : ?>
        <span class="author"><?= htmlspecialchars($author->getName()); ?></span>
      <? else : ?>
        <span class="author">Сообщение от удаленного пользователя</span>
      <? endif; ?>
      <div class="text"><?= htmlspecialchars(nl2br($message->getText())); ?></div>
      <? if ($message->getImage()) : ?>
        <div class="file">
          <img class="img" src="/images/<?= $message->getImage(); ?>" alt="">
        </div>
      <? endif; ?>
      <? if ($user->isAdmin()) : ?>
        <div class="admin">
          <a href="/admin/deleteMessage/?id=<?= $message->getId(); ?>">delete</a>
        </div>
      <? endif; ?>
    </div>
  <?php endforeach; ?>
<?php else : ?>
  сообщений пока нет
<?php endif; ?>

Добавить сообщение:
<div class="block">
  <form class="form" enctype="multipart/form-data" action="/blog/addMessage" method="post">
    <span class="field">
      <textarea class="input__text" type="text" value="" name="text"></textarea>
      Изображение: <input type="file" name="image">
      <input class="button" type="submit" value="Отправить">
    </span>
  </form>
</div>