<html>

<head>
  <style>
    html {font: 1em sans-serif; background: #7f7f7f; color: #ffff;}
    .main_title {color: #020102; text-align: center}
    .section {display: flex; justify-content: center; background: #3f3f3f; border-radius: 40px;}
    .block {margin-right: 30px;}
    .title {color: #d185a9;}
    .form {display: flex; flex-direction: column;}
    .field {display: flex; justify-content: space-between; margin-bottom: 5px;}
    .name_input {margin-right: 3px;}
    .button {margin-top: 10px; color: #d185a9; border-radius: 10px; padding: 10px }
  </style>
</head>

<body>
  <h3 class="main_title"><?= $this->title; ?></h3>
  <?php
  $user = $this->user;
  ?>

  <? if (!$user) : ?>
    <div class="section">
      <div class="block">
        <h3 class="title">Зарегистрироваться</h3>
        <form class="form" action="/login/register" method="post">
          <span class="field">
          <div class="name_input">Login:</div>
          <input type="text" value="" name="name">
          </span>
          <span class="field">
            <div class="name_input">Email:</div> 
            <input type="text" value="" name="email">
          </span>
          <span class="field">
            <div class="name_input">Password:</div> 
            <input type="text" value="" name="password">
          </span>
          <span class="field">
            <div class="name_input">Password_repeat:</div> 
            <input type="text" value="" name="password_2">
          </span>
          <input class="button" type="submit" value="Зарегистрироваться">
        </form>
      </div>

      <div class="block">
        <h3 class="title">Войти</h3>
        <form class="form" action="/login/auth" method="post">
          <span class="field">
            <div class="name_input">Email:</div> 
            <input type="text" value="" name="email">
          </span>
          <span class="field">
            <div class="name_input">Password:</div> 
            <input type="text" value="" name="password">
          </span>
          <input class="button" type="submit" value="Войти">
        </form>
      </div>
    </div>
  <? else : ?>
    Вы вошли как <?= $user->getName(); ?>
  <? endif; ?>

</body>

</html>